import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProfileProvider from "./core/providers/ProfileProvider";
import SideBar from "./components/dashboard/SideBar";
import DashHeader from "./components/DashHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen flex flex-col">
        <ProfileProvider>
          <div className="flex flex-row">
            <SideBar />
            <div className="w-full flex flex-col bg-gray-100">
              <DashHeader />
              {children}
            </div>
          </div>
        </ProfileProvider>
      </body>
    </html>
  );
}
